const ID="1M-vZ24Yw4ZN7R7b_473cVn8kny8DznTakSsD3VQsCzc",NATIONAL_ID="12Aty04yiLPPqz06AFDM8Y1Log2jEOqdXDqwiUV5yVX8", finished=new Set(["Delivered","Received","Completed"]); let inbound=[],outbound=[],costSummary={ytd:0,mtd:0,finished:0};
const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const sourceKey=v=>String(v).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
function parse(text){const a=text.indexOf("{"),b=text.lastIndexOf("}");if(a<0||b<0)throw Error("Google Sheets did not return data");return JSON.parse(text.slice(a,b+1)).table}
function objects(table){const headers=table.cols.map((c,i)=>(c.label||`COL_${i}`).toUpperCase().replace(/\s+/g," "));return table.rows.map(r=>Object.fromEntries(headers.map((h,i)=>{const c=r.c[i];return[h,c?(c.f??c.v??"").toString().trim():""]})))}
async function sheet(name,range,spreadsheetId=ID){const u=new URL(`https://docs.google.com/spreadsheets/d/${spreadsheetId}/gviz/tq`);u.searchParams.set("tqx","out:json");u.searchParams.set("headers","1");u.searchParams.set("sheet",name);if(range)u.searchParams.set("range",range);const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error(`${name}: ${r.status}`);return parse(await r.text())}
const get=(r,...n)=>{for(const k of n){const v=r[k.toUpperCase()];if(v)return v}return""}, useful=r=>Object.values(r).some(Boolean);
const parcelCarriers=/^(UPS|USPS|DHL|AMAZON|FEDEX)$/i;
function isInboundShipment(r){const shipment=get(r,"SHIPMENT"),container=get(r,"CONTAINER","CONTAINER RAW (SYSTEM)").replace(/\s/g,"").toUpperCase(),mbl=get(r,"MBL").replace(/\s/g,""),hasShipmentIdentifier=Boolean(shipment&&shipment!=="NEW")||/[A-Z]{4}\d{7}/.test(container)||/^\d{3}-?\d{8}$/.test(mbl),sectionLabel=Object.values(r).find(v=>parcelCarriers.test(String(v).trim()));return useful(r)&&hasShipmentIdentifier&&!sectionLabel}
function status(v){v=v.toLowerCase();if(/\bshipped\b|complete|closed|cancel/.test(v))return"Completed";if(/deliver/.test(v))return"Delivered";if(/receive/.test(v))return"Received";if(/shipping|transit|progress/.test(v))return"Shipping";return"Scheduled"}
function money(v){const m=String(v).replace(/,/g,"").match(/-?\d+(?:\.\d+)?/g);return m?m.reduce((s,n)=>s+Number(n),0):0}
function outboundCost(r){for(const n of ["INVOICE AMOUNT","RATE QUOTE AMOUNT","RATE QUOTE","QUOTE AMOUNT","QUOTE","RATE"]){const v=get(r,n);if(v)return money(v)}const invoice=get(r,"INVOICE");return invoice.includes("$")?money(invoice):0}
function formatDate(v){const m=String(v||"").match(/(\d{1,2})\/(\d{1,2})(?:\/(\d{2,4}))?/);if(!m)return String(v||"");const mo=+m[1];let y=m[3]?+m[3]:mo>=9?2025:2026;if(y<100)y+=2000;return`${String(mo).padStart(2,"0")}/${String(+m[2]).padStart(2,"0")}/${String(y).slice(-2)}`}
function lastDate(v){const matches=[...String(v||"").matchAll(/(\d{1,2})\/(\d{1,2})(?:\/(\d{2,4}))?/g)];return matches.length?formatDate(matches.at(-1)[0]):""}
function beforeJune2026(v){const m=String(v||"").match(/(\d{1,2})\/(\d{1,2})(?:\/(\d{2,4}))?/);if(!m)return false;const mo=+m[1];let y=m[3]?+m[3]:mo>=9?2025:2026;if(y<100)y+=2000;return new Date(y,mo-1,+m[2])<new Date(2026,5,1)}
function freight(r){return{qty:get(r,"QTY","QUANTITY","TOTAL CARTONS","PLT"),length:get(r,"LENGTH (IN)","LENGTH","L"),width:get(r,"WIDTH (IN)","WIDTH","W"),height:get(r,"HEIGHT (IN)","HEIGHT","H"),freightClass:get(r,"FREIGHT CLASS","CLASS"),subClass:get(r,"SUB CLASS","SUBCLASS")}}
function tracking(raw){const n=raw.replace(/\s/g,"").toUpperCase();if(!n)return["",""];if(n.startsWith("SMCU"))return["SM Line",`https://esvc.smlines.com/smline/CUP_HOM_3301GS.do?_search=false&f_cmd=121&page=1&rows=10000&search_name=${n}&search_type=C&sidx=&sord=asc`];if(/^(HMMU|HDMU)/.test(n))return["HMM",`https://www.hmm21.com/e-service/general/trackNTrace/TrackNTrace.do?searchType=CNTR&searchNo=${n}`];if(/^(MSCU|MEDU)/.test(n))return["MSC",`https://www.msc.com/en/track-a-shipment?trackingNumber=${n}`];if(/^(MAEU|MRKU)/.test(n))return["Maersk",`https://www.maersk.com/tracking/${n}`];return["Carrier tracking",`https://www.track-trace.com/container?number=${n}`]}
function parcelTracking(carrier,raw){const n=encodeURIComponent(raw.replace(/\s/g,""));if(carrier==="UPS")return`https://www.ups.com/track?loc=en_US&tracknum=${n}`;if(carrier==="USPS")return`https://tools.usps.com/go/TrackConfirmAction?tLabels=${n}`;if(carrier==="DHL")return`https://www.dhl.com/us-en/home/tracking.html?tracking-id=${n}`;if(carrier==="FedEx")return`https://www.fedex.com/fedextrack/?trknbr=${n}`;return""}
function parcelInbound(table,startId){let carrier="";const result=[],value=(row,i)=>{const c=row.c?.[i];return c?(c.f??c.v??"").toString().trim():""};for(const row of table.rows){const section=value(row,0);if(parcelCarriers.test(section))carrier=/^fedex$/i.test(section)?"FedEx":section.toUpperCase();const number=value(row,1).replace(/^TRACKING#$/i,"").trim();if(!carrier||!number||/^TRACK/i.test(number))continue;const invoice=value(row,2),detail=value(row,4);result.push({id:startId+result.length,mode:"Small Parcel",eta:lastDate(detail),shipmentNo:invoice||number,mbl:"",hbl:invoice,container:number,carrier,trackingUrl:parcelTracking(carrier,number),origin:value(row,3)||"Imports",destination:"StyleKorean warehouse",status:status(detail)})}return result}
function out(source,r,map){const mapped=map(r);outbound.push({id:outbound.length+1,source,...freight(r),...mapped,shipDate:formatDate(mapped.shipDate),rate:outboundCost(r),cancelled:/cancel/i.test(Object.values(r).join(" ")),status:beforeJune2026(mapped.shipDate)?"Completed":mapped.status})}
async function load(){ $("sync").textContent="Importing outbound and inbound sources…";try{const sources=[["IMPORTS","A1:AD340"],["TRANSFERS","A1:N974"],["ULTA","A1:N1012"],["IHERB","A1:M967"],["B2B/E-COM TRUCKING","A1:R853"],["WH Trucking Request","A2:U1551"],["NATIONAL ORDER PROGRESS","A1:U2504",NATIONAL_ID]],results=await Promise.allSettled(sources.map(args=>sheet(...args))),tables=results.map(result=>result.status==="fulfilled"?result.value:{cols:[],rows:[]}),unavailable=results.flatMap((result,i)=>result.status==="rejected"?[sources[i][0]]:[]);const [im,tr,ul,ih,b2,whRows,national]=tables.map(objects),wh=whRows.slice(1);
inbound=im.filter(isInboundShipment).map((r,i)=>{const container=get(r,"CONTAINER","CONTAINER RAW (SYSTEM)").split(/[,\n]/)[0],mbl=get(r,"MBL"),[carrier,trackingUrl]=tracking(container);return{id:i+1,mode:container||!/^\d{3}-?\d+/.test(mbl)?"Ocean":"Air",eta:formatDate(get(r,"ETA")),shipmentNo:get(r,"SHIPMENT"),mbl,hbl:get(r,"HBL"),container,carrier,trackingUrl,origin:get(r,"VSL")||"Korea / Asia",destination:"Los Angeles / Long Beach, CA",status:status(`${get(r,"NOTES")} ${get(r,"RESERVED")} ${get(r,"DELIVERY EXPECTED")}`)}});inbound.push(...parcelInbound(tables[0],inbound.length+1));outbound=[];
tr.filter(useful).forEach(r=>out("Transfers",r,r=>({shipDate:get(r,"PU"),customer:get(r,"TO"),invoice:get(r,"INVOICE"),origin:get(r,"VENDOR/SUPPLIER/ORIGIN","VENDOR / SUPPLIER / ORIGIN","VENDOR","SUPPLIER","ORIGIN"),carrier:get(r,"TRUCKING"),pro:get(r,"BOL#"),units:get(r,"PLT")?`${get(r,"PLT")} Pallets`:"",destination:get(r,"TO"),rate:money(get(r,"RATE")),status:status(`${get(r,"STATUS")} ${get(r,"NOTE")} ${get(r,"INVOICE")}`)})));
ul.filter(useful).forEach(r=>out("Ulta",r,r=>({shipDate:get(r,"SHIP DATE","DATE"),customer:get(r,"DC")||"Ulta",invoice:get(r,"PO#","INVOICE"),carrier:get(r,"TRUCKING"),pro:get(r,"PRO#"),units:get(r,"TOTAL CARTONS")?`${get(r,"TOTAL CARTONS")} Cartons`:"",destination:get(r,"SHIP TO"),rate:money(get(r,"RATE")),status:get(r,"PRO#")?"Completed":status(`${get(r,"STATUS")} ${get(r,"NOTE")} ${get(r,"REMARKS")}`)})));
ih.filter(useful).forEach(r=>out("iHerb",r,r=>({shipDate:get(r,"PU","DELIVERY APPT"),customer:"iHerb",invoice:get(r,"PO#"),carrier:get(r,"TRUCKING"),pro:get(r,"BOL"),units:get(r,"QTY")?`${get(r,"QTY")} Pallets`:"",destination:get(r,"TO"),rate:money(get(r,"RATE")),status:status(`${get(r,"STATUS")} ${get(r,"NOTE")} ${get(r,"REMARKS")}`)})));
b2.filter(r=>["INVOICE","PU","TRUCKING","PRO#","PLT","QTY","RATE"].some(name=>get(r,name))).forEach(r=>out("B2B/E-com Trucking",r,r=>({shipDate:get(r,"PU"),customer:get(r,"NOTE"),invoice:get(r,"INVOICE"),carrier:get(r,"TRUCKING"),pro:get(r,"PRO#"),units:get(r,"PLT")?`${get(r,"PLT")} Pallets`:"",destination:get(r,"TO"),rate:money(get(r,"RATE")),status:status(Object.values(r).join(" "))})));
wh.filter(r=>!/PLEASE LIST THE INVOICE WITH SHIPPING CHARGE/i.test(get(r,"CUSTOMER"))&&["CUSTOMER","INVOICE NO.","SHIP DATE","PALLET TYPE","CARRIER","PRO#"].some(name=>get(r,name))).forEach(r=>out("WH Trucking Request",r,r=>({shipDate:get(r,"SHIP DATE"),customer:get(r,"CUSTOMER"),invoice:get(r,"INVOICE NO."),carrier:get(r,"CARRIER"),pro:get(r,"PRO#"),units:get(r,"PALLET TYPE")?"Pallets":"",destination:get(r,"ADDRESS"),rate:money(get(r,"RATE")),status:status(`${get(r,"STATUS")} ${get(r,"NOTE")} ${get(r,"REMARKS")}`)})));
national.filter(useful).forEach(r=>out("National Order Progress",r,r=>({shipDate:get(r,"PICK-UP DATE","START SHIP"),customer:get(r,"CHANNEL"),invoice:get(r,"PO#","ORDER#"),origin:get(r,"DEPARTMENT"),carrier:get(r,"SHIPMENT TYPE"),pro:"",units:get(r,"MEMO"),destination:"",rate:0,status:status(`${get(r,"OVERALL PO STATUS")} ${get(r,"MEMO")}`)})));
const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),dated=outbound.map(r=>({r,d:date(r.shipDate)})).filter(x=>x.d&&x.d<=today);costSummary={ytd:dated.filter(x=>x.d.getFullYear()===now.getFullYear()).reduce((s,x)=>s+x.r.rate,0),mtd:dated.filter(x=>x.d.getFullYear()===now.getFullYear()&&x.d.getMonth()===now.getMonth()).reduce((s,x)=>s+x.r.rate,0),finished:outbound.filter(r=>!r.cancelled&&finished.has(r.status)).length};outbound=outbound.filter(r=>!finished.has(r.status));
populate();render();$("sync").textContent=unavailable.length?`${7-unavailable.length} sources imported · unavailable: ${unavailable.join(", ")}`:"All seven outbound/inbound sources imported";$("dot").classList.toggle("sync-error",unavailable.length>0);$("updated").textContent=new Date().toLocaleString();}catch(e){$("dot").classList.add("sync-error");$("sync").textContent=`Workbook sync issue: ${e.message}`;console.error(e)}}
function date(v){const m=String(v).match(/(\d{1,2})\/(\d{1,2})(?:\/(\d{2,4}))?/);if(!m)return null;const mo=+m[1];let y=m[3]?+m[3]:mo>=9?2025:2026;if(y<100)y+=2000;return new Date(y,mo-1,+m[2])}function soon(v){const d=date(v);if(!d)return false;const a=new Date();a.setHours(0,0,0,0);return d>=a&&d<=new Date(+a+14*864e5)}
function populate(){const fill=(id,vals)=>{const s=$(id),first=s.firstElementChild;s.innerHTML="";s.append(first);[...new Set(vals.filter(Boolean))].sort().forEach(v=>s.insertAdjacentHTML("beforeend",`<option>${esc(v)}</option>`))};fill("source",outbound.map(r=>r.source));fill("outStatus",outbound.map(r=>r.status))}
function render(){const activeOutbound=outbound.filter(r=>!finished.has(r.status)).length,active=inbound.filter(r=>!finished.has(r.status)).length,cost=outbound.filter(r=>!finished.has(r.status)).reduce((a,r)=>a+r.rate,0);$("metrics").innerHTML=[["Active outbound shipments",activeOutbound,"Completed and grey rows excluded"],["Delivered / completed",costSummary.finished,"All finished outbound source rows"],["Inbound active",active,"Ocean + air + parcel"],["Inbound ocean",inbound.filter(r=>r.mode==="Ocean").length,"Container shipments"],["Small parcel",inbound.filter(r=>r.mode==="Small Parcel").length,"UPS / FedEx / DHL + more"],["Scheduled outbound cost",`$${cost.toLocaleString()}`,"Active numeric charge rows"],["Year-to-date outbound cost",`$${costSummary.ytd.toLocaleString()}`,"Invoice or quoted charges through today"],["Month-to-date outbound cost",`$${costSummary.mtd.toLocaleString()}`,"Invoice or quoted charges this month"]].map((m,i)=>`<article class="metric-card ${i===5?"accent-card":i===6?"ytd-card":i===7?"mtd-card":""}"><span>${m[0]}</span><strong>${m[1]}</strong><small>${m[2]}</small></article>`).join("");upcoming("inboundUpcoming",inbound.filter(r=>!finished.has(r.status)&&soon(r.eta)),"in");upcoming("outboundUpcoming",outbound.filter(r=>!finished.has(r.status)&&soon(r.shipDate)),"out");renderOut();renderIn()}
function upcoming(id,rows,type){const start=new Date();start.setHours(0,0,0,0);const days=Array.from({length:14},(_,i)=>new Date(+start+i*864e5));$(id).innerHTML=`<div class="schedule-scroll"><div class="schedule-grid">${days.map(day=>{const matches=rows.filter(r=>{const d=date(type==="in"?r.eta:r.shipDate);return d&&d.toDateString()===day.toDateString()});const heading=matches.length?(matches.some(r=>r.status==="Shipping")?"IN TRANSIT":"ESTIMATED / CHANGED"):"&nbsp;";return`<div class="schedule-day"><div class="schedule-status ${heading==="IN TRANSIT"?"status-transit":matches.length?"status-estimated":""}">${heading}</div><div class="schedule-date-label">${day.toLocaleDateString("en-US",{month:"2-digit",day:"2-digit",year:"2-digit"})}</div><div class="schedule-cell">${matches.map(r=>{const label=r.shipmentNo||r.container||r.hbl||r.mbl,detail=r.container||r.carrier,cls=type==="in"?"schedule-inbound-item":`schedule-source-${sourceKey(r.source)}`;return type==="in"?`<div class="schedule-item ${cls}"><strong>${esc(label||"Shipment")}</strong><span>${esc(detail)}</span></div>`:`<div class="schedule-item ${cls}"><div class="schedule-outbound-fields"><span><b>Customer</b>${esc(r.customer)||"—"}</span><span><b>Invoice</b>${esc(r.invoice)||"—"}</span></div><small>${esc(r.source)}${r.pro?` · ${esc(r.pro)}`:""}</small></div>`}).join("")}</div></div>`}).join("")}</div></div>`}
function renderOut(){const q=$("outSearch").value.toLowerCase(),src=$("source").value,st=$("outStatus").value,rows=outbound.filter(r=>!finished.has(r.status)&&(!q||Object.values(r).join(" ").toLowerCase().includes(q))&&(!src||r.source===src)&&(!st||r.status===st)).sort((a,b)=>(date(a.shipDate)?.getTime()??Number.MAX_SAFE_INTEGER)-(date(b.shipDate)?.getTime()??Number.MAX_SAFE_INTEGER));$("outCount").textContent=`${rows.length} rows`;$("outRows").innerHTML=rows.map(r=>`<tr class="row-source-${sourceKey(r.source)}"><td><span class="source-tag source-${sourceKey(r.source)}">${esc(r.source)}</span></td><td class="date-cell">${esc(r.shipDate)}</td><td><strong>${esc(r.customer)}</strong><small>${esc(r.invoice)}</small></td><td>${esc(r.origin)||"—"}</td><td><strong>${esc(r.carrier)}</strong><small>${esc(r.pro)}</small></td><td>${esc(r.units)}</td><td>${esc(r.qty)||"—"}</td><td>${esc(r.length)||"—"}</td><td>${esc(r.width)||"—"}</td><td>${esc(r.height)||"—"}</td><td>${esc(r.freightClass)||"—"}</td><td>${esc(r.subClass)||"—"}</td><td>${esc(r.destination)}</td><td class="money">$${r.rate.toLocaleString()}</td><td><span class="status-select status-${r.status.toLowerCase()}">${r.status}</span></td></tr>`).join("")}
function renderIn(){const q=$("inSearch").value.toLowerCase(),mode=$("mode").value,rows=inbound.filter(r=>!finished.has(r.status)&&(!q||Object.values(r).join(" ").toLowerCase().includes(q))&&(!mode||r.mode===mode));$("inCount").textContent=`${rows.length} rows`;$("inRows").innerHTML=rows.map(r=>`<tr><td><span class="mode-tag mode-${r.mode.toLowerCase()}">${r.mode}</span></td><td class="date-cell">${esc(r.eta)}</td><td><strong>${esc(r.shipmentNo)}</strong><small>Imports</small></td><td>${esc(r.mbl)||"—"}</td><td>${esc(r.hbl)||"—"}</td><td>${r.container?`<a class="container-link" target="_blank" rel="noreferrer" href="${esc(r.trackingUrl)}">${esc(r.container)} →</a>`:"—"}</td><td>${esc(r.carrier)}</td><td><strong>${esc(r.origin)}</strong><small>to ${esc(r.destination)}</small></td><td><span class="status-select status-${r.status.toLowerCase()}">${r.status}</span></td></tr>`).join("")}
["outSearch","source","outStatus"].forEach(id=>$(id).addEventListener("input",renderOut));["inSearch","mode"].forEach(id=>$(id).addEventListener("input",renderIn));$("refresh").addEventListener("click",load);load();
